# Generated by Django 3.2.4 on 2021-06-15 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('class_cordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('total_grades', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_class_attended', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('assignment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('number_of_participants', models.IntegerField(blank=True, default=0, null=True)),
                ('meeting_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_start_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('join_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.student')),
            ],
        ),
    ]
