# Generated by Django 3.2.4 on 2021-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='assignment_name',
        ),
        migrations.AddField(
            model_name='grades',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
