# Generated by Django 3.1.6 on 2021-06-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='meeting_start_time',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='meeting_title',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='number_of_participants',
        ),
    ]
